version: '3.8'

services:
  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=discord_bot
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    ports:
      - "8000:8000" # Map the host's port 8000 to the container's port 8000
    networks:
      - isolated_network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=discord_bot
    ports:
      - "27017:27017" # Map the host's port 27017 to the container's port 27017
    networks:
      - isolated_network

networks:
  isolated_network:
    driver: bridge
