version: '3.8'

services:
  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "3005:3005" # Map the host's port 8000 to the container's port 8000
    links:
      - mongodb
    networks:
      - isolated_network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017" # Map the host's port 27017 to the container's port 27017
    networks:
      - isolated_network

networks:
  isolated_network: