name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number for the release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mobatome/discordai:${{ inputs.version }}

      - name: Create release branch
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Create release branch'
          branch: main
          title: 'Create release branch'
          body: 'Automatically created by GitHub Actions.'
          base: 'main'
          head: 'release/${{ inputs.version }}'
          draft: false

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge release branch into main'
          branch: main
          title: 'Merge release branch into main'
          body: 'Automatically created by GitHub Actions.'
          base: 'main'
          head: 'release/${{ inputs.version }}'
          draft: false
